import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { dbConnect } from "./services/mongo";
import AuthProvider from "./providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnect();
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <main className="py-8">
            <Navbar />
            {children}
          </main>
        </body>
      </AuthProvider>
    </html>
  );
}
